#!/bin/bash

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc
	

# Check
path1=/usr/share/themes/Moe-Orange13
path2=/usr/share/themes/Moe-Pink13
path3=/usr/share/themes/Moe-Purple13
path4=/usr/share/themes/Moe-Red13
path5=/usr/share/themes/Moe-Yellow13
path6=/usr/share/themes/Moe-Black13

if [ "$1" == "-c" ] ; then
	if [ -d $path1 ] && [ -d $path2 ] && [ -d $path3 ] && [ -d $path4 ] && [ -d $path5 ]  ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	#GITのインストール確認
	if [ $(dpkg-query -W -f='${Status}' git  2>/dev/null | grep -c "ok installed") -eq 1 ];
	then
		echo "gitは、インストールされています。"

	else
		echo "gitを、インストールします"
		sudo apt install git -y
	fi
 
	git clone https://github.com/megamuteki/moebuntu.git
	_log "MoeBuntuThemeのダウンロードに成功しました。"
	cd moebuntu
	
	dir=$(pwd)
	sudo tar xf $dir/themes/Moe-Orange13.tar.xz -C /usr/share/themes
	sudo tar xf $dir/themes/Moe-Pink13.tar.xz -C /usr/share/themes
	sudo tar xf $dir/themes/Moe-Purple13.tar.xz -C /usr/share/themes
	sudo tar xf $dir/themes/Moe-Red13.tar.xz -C /usr/share/themes
	sudo tar xf $dir/themes/Moe-Yellow13.tar.xz -C /usr/share/themes
	rm -rf $dir 
	_log "MoeBuntuThemeのインストールに成功しました。"

		
# Purge
elif [ "$1" == "-p" ] ; then
	sudo rm -rf /usr/share/themes/Moe-Pink13
	sudo rm -rf /usr/share/themes/Moe-Yellow13
	sudo rm -rf /usr/share/themes/Moe-Orange13
	sudo rm -rf /usr/share/themes/Moe-Red13
	sudo rm -rf /usr/share/themes/Moe-Purple13
	_log "MoeBuntuThemeのアンインストールに成功しました。"

fi
